import type { Abi } from "viem";

export interface CadenceDeployment {
  poolManager: `0x${string}`;
  usdc: `0x${string}`;
  slots: `0x${string}`;
  hook: `0x${string}`;
  router: `0x${string}`;
  lambdaBps: number;
  epochLengthBlocks: number;
  pricePerEth: string;
}

/** Fetch the deployment manifest generated by contracts/script/DeployCadence.s.sol. */
export async function loadDeployment(chainId: number): Promise<CadenceDeployment | null> {
  try {
    const res = await fetch(`/deployments/${chainId}.json`, { cache: "no-store" });
    if (!res.ok) return null;
    const raw = (await res.json()) as Record<string, unknown>;
    const req = ["poolManager", "usdc", "slots", "hook", "router"] as const;
    if (req.some((k) => typeof raw[k] !== "string")) return null;
    return {
      poolManager: raw.poolManager as `0x${string}`,
      usdc: raw.usdc as `0x${string}`,
      slots: raw.slots as `0x${string}`,
      hook: raw.hook as `0x${string}`,
      router: raw.router as `0x${string}`,
      lambdaBps: Number(raw.lambdaBps ?? 0),
      epochLengthBlocks: Number(raw.epochLengthBlocks ?? 0),
      pricePerEth: String(raw.pricePerEth ?? "0"),
    };
  } catch {
    return null;
  }
}

/** ERC-1155 slots: fixed-price mint, commit-reveal, consumption. */
export const slotsAbi = [
  { type: "function", name: "mintPublic", stateMutability: "payable", inputs: [{ name: "size", type: "uint256" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "commitMint", stateMutability: "payable", inputs: [{ name: "H", type: "bytes32" }], outputs: [] },
  { type: "function", name: "revealAndConsume", stateMutability: "nonpayable", inputs: [{ name: "trader", type: "address" }, { name: "size", type: "uint256" }, { name: "salt", type: "bytes32" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "consume", stateMutability: "nonpayable", inputs: [{ name: "trader", type: "address" }, { name: "size", type: "uint256" }], outputs: [] },
  { type: "function", name: "expire", stateMutability: "nonpayable", inputs: [{ name: "epochId", type: "uint256" }], outputs: [] },
  { type: "function", name: "expireCommitment", stateMutability: "nonpayable", inputs: [{ name: "H", type: "bytes32" }], outputs: [] },
  { type: "function", name: "commitHash", stateMutability: "pure", inputs: [{ name: "size", type: "uint256" }, { name: "epochId", type: "uint256" }, { name: "salt", type: "bytes32" }], outputs: [{ name: "", type: "bytes32" }] },
  { type: "function", name: "slotOf", stateMutability: "view", inputs: [{ name: "owner", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "currentEpoch", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "pricePerEth", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "remainingCapacity", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "commitments", stateMutability: "view", inputs: [{ name: "", type: "bytes32" }], outputs: [{ name: "payer", type: "address" }, { name: "epochId", type: "uint256" }, { name: "escrow", type: "uint256" }, { name: "reserved", type: "uint256" }, { name: "status", type: "uint8" }] },
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "", type: "address" }, { name: "", type: "uint256" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "event", name: "SlotMinted", inputs: [{ name: "epochId", type: "uint256", indexed: true }, { name: "buyer", type: "address", indexed: true }, { name: "size", type: "uint256", indexed: false }, { name: "pricePaid", type: "uint256", indexed: false }] },
  { type: "event", name: "SlotCommitted", inputs: [{ name: "epochId", type: "uint256", indexed: true }, { name: "H", type: "bytes32", indexed: true }, { name: "payer", type: "address", indexed: true }, { name: "escrow", type: "uint256", indexed: false }] },
  { type: "event", name: "SlotRevealed", inputs: [{ name: "epochId", type: "uint256", indexed: true }, { name: "H", type: "bytes32", indexed: true }, { name: "trader", type: "address", indexed: true }, { name: "size", type: "uint256", indexed: false }, { name: "consumed", type: "uint256", indexed: false }] },
  { type: "event", name: "SlotConsumed", inputs: [{ name: "epochId", type: "uint256", indexed: true }, { name: "trader", type: "address", indexed: true }, { name: "size", type: "uint256", indexed: false }] },
  { type: "event", name: "SlotExpired", inputs: [{ name: "epochId", type: "uint256", indexed: true }, { name: "holder", type: "address", indexed: true }, { name: "size", type: "uint256", indexed: false }] },
  { type: "event", name: "CommitmentExpired", inputs: [{ name: "epochId", type: "uint256", indexed: true }, { name: "H", type: "bytes32", indexed: true }, { name: "payer", type: "address", indexed: true }, { name: "escrowRefunded", type: "uint256", indexed: false }] },
] as const;

/** PA-AMM hook: active/passive reserves, custom-curve beforeSwap. */
export const hookAbi = [
  { type: "function", name: "reserves", stateMutability: "view", inputs: [], outputs: [{ name: "activeEth", type: "uint256" }, { name: "activeUsdc", type: "uint256" }, { name: "passiveEth", type: "uint256" }, { name: "passiveUsdc", type: "uint256" }] },
  { type: "function", name: "quoteOutUsdc", stateMutability: "view", inputs: [{ name: "sizeEth", type: "uint256" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "epochCapacityEth", stateMutability: "view", inputs: [{ name: "", type: "uint256" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "currentEpoch", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "refreshEpoch", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "event", name: "CadenceSwap", inputs: [{ name: "epochId", type: "uint256", indexed: true }, { name: "trader", type: "address", indexed: true }, { name: "zeroForOne", type: "bool", indexed: false }, { name: "sizeInEth", type: "uint256", indexed: false }, { name: "outAmount", type: "uint256", indexed: false }, { name: "fromCommitment", type: "bool", indexed: false }] },
  { type: "event", name: "EpochRefreshed", inputs: [{ name: "epochId", type: "uint256", indexed: true }, { name: "activeEth", type: "uint256", indexed: false }, { name: "activeUsdc", type: "uint256", indexed: false }, { name: "passiveEth", type: "uint256", indexed: false }, { name: "passiveUsdc", type: "uint256", indexed: false }] },
] as const;

/** Router: swap (public path) + sellEthPrivate (reveal path). */
export const routerAbi = [
  { type: "function", name: "swap", stateMutability: "payable", inputs: [{ name: "key", type: "tuple", components: [{ name: "currency0", type: "address" }, { name: "currency1", type: "address" }, { name: "fee", type: "uint24" }, { name: "tickSpacing", type: "int24" }, { name: "hooks", type: "address" }] }, { name: "zeroForOne", type: "bool" }, { name: "amountIn", type: "uint256" }], outputs: [{ name: "", type: "int256" }] },
  { type: "function", name: "sellEthPrivate", stateMutability: "payable", inputs: [{ name: "key", type: "tuple", components: [{ name: "currency0", type: "address" }, { name: "currency1", type: "address" }, { name: "fee", type: "uint24" }, { name: "tickSpacing", type: "int24" }, { name: "hooks", type: "address" }] }, { name: "sizeEth", type: "uint256" }, { name: "salt", type: "bytes32" }], outputs: [{ name: "", type: "int256" }] },
] as const;

/** MockUSDC / quote token — only what the UI needs. */
export const usdcAbi = [
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "approve", stateMutability: "nonpayable", inputs: [{ name: "", type: "address" }, { name: "", type: "uint256" }], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "string" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint8" }] },
] as const;

/**
 * LP module — the accounting surface the Cadence hook will implement
 * (deposit → capacity → slot-sale revenue → withdraw with safety bounds).
 * The /lp dashboard reads and writes against this ABI today and shows
 * honest "waiting for LP module" states until the backend lands.
 *
 * Backend contract (must match for the UI to light up):
 *   depositEth() payable                                   0x439370b1
 *   withdrawEth(uint256 shares)                            reverts UnsafeWithdraw() 0x067a3d2e
 *   sharesOf(address) view → uint256
 *   lpPosition(address) view → (depositedEth, shares, claimableRevenueEth, claimableSwapFeesUsdc, withdrawableEth)
 *   swapFeeBps() view → uint256
 *   slotRevenueShareBps() view → uint256
 *   soldCapacityEth() view → uint256   // sold + committed capacity this epoch
 * Events: LPDeposited(lp, ethIn, shares) · LPWithdrawn(lp, shares, ethOut)
 *         SlotRevenueAccrued(epochId, proceeds) · SwapFeeAccrued(epochId, feeUsdc)
 */
export const lpModuleAbi = [
  { type: "function", name: "depositEth", stateMutability: "payable", inputs: [], outputs: [{ name: "shares", type: "uint256" }] },
  { type: "function", name: "withdrawEth", stateMutability: "nonpayable", inputs: [{ name: "shares", type: "uint256" }], outputs: [{ name: "ethOut", type: "uint256" }] },
  { type: "function", name: "sharesOf", stateMutability: "view", inputs: [{ name: "", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "lpPosition", stateMutability: "view", inputs: [{ name: "", type: "address" }], outputs: [{ name: "depositedEth", type: "uint256" }, { name: "shares", type: "uint256" }, { name: "claimableRevenueEth", type: "uint256" }, { name: "claimableSwapFeesUsdc", type: "uint256" }, { name: "withdrawableEth", type: "uint256" }] },
  { type: "function", name: "swapFeeBps", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "slotRevenueShareBps", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "soldCapacityEth", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "event", name: "LPDeposited", inputs: [{ name: "lp", type: "address", indexed: true }, { name: "ethIn", type: "uint256", indexed: false }, { name: "shares", type: "uint256", indexed: false }] },
  { type: "event", name: "LPWithdrawn", inputs: [{ name: "lp", type: "address", indexed: true }, { name: "shares", type: "uint256", indexed: false }, { name: "ethOut", type: "uint256", indexed: false }] },
  { type: "event", name: "SlotRevenueAccrued", inputs: [{ name: "epochId", type: "uint256", indexed: true }, { name: "proceeds", type: "uint256", indexed: false }] },
  { type: "event", name: "SwapFeeAccrued", inputs: [{ name: "epochId", type: "uint256", indexed: true }, { name: "feeUsdc", type: "uint256", indexed: false }] },
] as const;

/** PoolKey struct type for viem writes. */
export function poolKey(d: CadenceDeployment) {
  return {
    currency0: "0x0000000000000000000000000000000000000000" as const,
    currency1: d.usdc,
    fee: 0,
    tickSpacing: 60,
    hooks: d.hook,
  };
}

export type CadenceAbis = typeof slotsAbi | typeof hookAbi | typeof routerAbi | typeof usdcAbi;
export type AbiLike = Abi;
